-- 0001_init.sql -- Initial schema for huck.
--
-- Migrations are append-only. Do not edit this file once released; create a
-- new migrations/NNNN_<name>.sql instead.

CREATE TABLE users (
    id            INTEGER PRIMARY KEY,
    handle        TEXT    NOT NULL UNIQUE,    -- lowercased in Go
    email         TEXT    NOT NULL UNIQUE,    -- lowercased in Go
    password_hash TEXT    NOT NULL,           -- bcrypt
    is_admin      INTEGER NOT NULL DEFAULT 0, -- 0 = user, 1 = admin
    created_at    TEXT    NOT NULL,           -- ISO-8601 UTC
    updated_at    TEXT    NOT NULL
);

CREATE TABLE invites (
    token        TEXT PRIMARY KEY,             -- 32 bytes, base64url
    email        TEXT NOT NULL,                -- lowercased in Go
    invited_by   INTEGER NOT NULL REFERENCES users(id),
    created_at   TEXT NOT NULL,
    expires_at   TEXT NOT NULL,                -- = created_at + 7d
    consumed_at  TEXT                          -- NULL until used
);
-- Enforces "one active invite per email": admins must delete or
-- consume the existing invite before creating another for the same
-- address. Resend reuses the existing row, so this constraint does
-- not block legitimate workflows.
CREATE UNIQUE INDEX invites_email_active
    ON invites(email) WHERE consumed_at IS NULL;

CREATE TABLE schema_migrations (
    version    INTEGER PRIMARY KEY,
    applied_at TEXT    NOT NULL
);
